version: '3.8'

services:
  web:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev -- -p 8090
