version: '3.8'

services:
  web:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG:-latest}
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm start
